/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAntiraidRouteImport } from './routes/_authenticated/antiraid'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAutomodRouteImport } from './routes/_authenticated/automod'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedCommandsRouteImport } from './routes/_authenticated/commands'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedPollsRouteImport } from './routes/_authenticated/polls'
import { Route as AuthenticatedRanksRouteImport } from './routes/_authenticated/ranks'
import { Route as AuthenticatedSanctionsRouteImport } from './routes/_authenticated/sanctions'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedStaffRolesRouteImport } from './routes/_authenticated/staff-roles'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedVersionsRouteImport } from './routes/_authenticated/versions'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedAnnouncementsIndexRouteImport } from './routes/_authenticated/announcements/index'
import { Route as AuthenticatedAnnouncementsIdRouteImport } from './routes/_authenticated/announcements/$id'
import { Route as AuthenticatedTicketIdRouteImport } from './routes/_authenticated/ticket.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAntiraidRoute = AuthenticatedAntiraidRouteImport.update({
  id: '/antiraid',
  path: '/antiraid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomodRoute = AuthenticatedAutomodRouteImport.update({
  id: '/automod',
  path: '/automod',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandsRoute = AuthenticatedCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPollsRoute = AuthenticatedPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRanksRoute = AuthenticatedRanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSanctionsRoute = AuthenticatedSanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRolesRoute = AuthenticatedStaffRolesRouteImport.update({
  id: '/staff-roles',
  path: '/staff-roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVersionsRoute = AuthenticatedVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsIndexRoute =
  AuthenticatedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIdRoute =
  AuthenticatedAnnouncementsIdRouteImport.update({
    id: '/announcements/$id',
    path: '/announcements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketIdRoute = AuthenticatedTicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/antiraid': typeof AuthenticatedAntiraidRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/automod': typeof AuthenticatedAutomodRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/commands': typeof AuthenticatedCommandsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/events': typeof AuthenticatedEventsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/sanctions': typeof AuthenticatedSanctionsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/staff-roles': typeof AuthenticatedStaffRolesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/ticket/$id': typeof AuthenticatedTicketIdRoute
  '/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/antiraid': typeof AuthenticatedAntiraidRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/automod': typeof AuthenticatedAutomodRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/commands': typeof AuthenticatedCommandsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/events': typeof AuthenticatedEventsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/sanctions': typeof AuthenticatedSanctionsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/staff-roles': typeof AuthenticatedStaffRolesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/': typeof AuthenticatedIndexRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/ticket/$id': typeof AuthenticatedTicketIdRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/antiraid': typeof AuthenticatedAntiraidRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/automod': typeof AuthenticatedAutomodRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/commands': typeof AuthenticatedCommandsRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/polls': typeof AuthenticatedPollsRoute
  '/_authenticated/ranks': typeof AuthenticatedRanksRoute
  '/_authenticated/sanctions': typeof AuthenticatedSanctionsRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/staff-roles': typeof AuthenticatedStaffRolesRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/versions': typeof AuthenticatedVersionsRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/_authenticated/ticket/$id': typeof AuthenticatedTicketIdRoute
  '/_authenticated/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/antiraid'
    | '/audit'
    | '/automod'
    | '/changelog'
    | '/commands'
    | '/console'
    | '/events'
    | '/logs'
    | '/members'
    | '/messages'
    | '/network'
    | '/onboarding'
    | '/people'
    | '/permissions'
    | '/polls'
    | '/ranks'
    | '/sanctions'
    | '/sessions'
    | '/staff-roles'
    | '/stats'
    | '/tickets'
    | '/versions'
    | '/voice'
    | '/announcements/$id'
    | '/ticket/$id'
    | '/announcements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/antiraid'
    | '/audit'
    | '/automod'
    | '/changelog'
    | '/commands'
    | '/console'
    | '/events'
    | '/logs'
    | '/members'
    | '/messages'
    | '/network'
    | '/onboarding'
    | '/people'
    | '/permissions'
    | '/polls'
    | '/ranks'
    | '/sanctions'
    | '/sessions'
    | '/staff-roles'
    | '/stats'
    | '/tickets'
    | '/versions'
    | '/voice'
    | '/'
    | '/announcements/$id'
    | '/ticket/$id'
    | '/announcements'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/antiraid'
    | '/_authenticated/audit'
    | '/_authenticated/automod'
    | '/_authenticated/changelog'
    | '/_authenticated/commands'
    | '/_authenticated/console'
    | '/_authenticated/events'
    | '/_authenticated/logs'
    | '/_authenticated/members'
    | '/_authenticated/messages'
    | '/_authenticated/network'
    | '/_authenticated/onboarding'
    | '/_authenticated/people'
    | '/_authenticated/permissions'
    | '/_authenticated/polls'
    | '/_authenticated/ranks'
    | '/_authenticated/sanctions'
    | '/_authenticated/sessions'
    | '/_authenticated/staff-roles'
    | '/_authenticated/stats'
    | '/_authenticated/tickets'
    | '/_authenticated/versions'
    | '/_authenticated/voice'
    | '/_authenticated/'
    | '/_authenticated/announcements/$id'
    | '/_authenticated/ticket/$id'
    | '/_authenticated/announcements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/antiraid': {
      id: '/_authenticated/antiraid'
      path: '/antiraid'
      fullPath: '/antiraid'
      preLoaderRoute: typeof AuthenticatedAntiraidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automod': {
      id: '/_authenticated/automod'
      path: '/automod'
      fullPath: '/automod'
      preLoaderRoute: typeof AuthenticatedAutomodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commands': {
      id: '/_authenticated/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof AuthenticatedCommandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/polls': {
      id: '/_authenticated/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthenticatedPollsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranks': {
      id: '/_authenticated/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof AuthenticatedRanksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sanctions': {
      id: '/_authenticated/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof AuthenticatedSanctionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-roles': {
      id: '/_authenticated/staff-roles'
      path: '/staff-roles'
      fullPath: '/staff-roles'
      preLoaderRoute: typeof AuthenticatedStaffRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versions': {
      id: '/_authenticated/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof AuthenticatedVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/': {
      id: '/_authenticated/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/$id': {
      id: '/_authenticated/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket/$id': {
      id: '/_authenticated/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof AuthenticatedTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAntiraidRoute: typeof AuthenticatedAntiraidRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedAutomodRoute: typeof AuthenticatedAutomodRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedCommandsRoute: typeof AuthenticatedCommandsRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPollsRoute: typeof AuthenticatedPollsRoute
  AuthenticatedRanksRoute: typeof AuthenticatedRanksRoute
  AuthenticatedSanctionsRoute: typeof AuthenticatedSanctionsRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedStaffRolesRoute: typeof AuthenticatedStaffRolesRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedVersionsRoute: typeof AuthenticatedVersionsRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnnouncementsIdRoute: typeof AuthenticatedAnnouncementsIdRoute
  AuthenticatedTicketIdRoute: typeof AuthenticatedTicketIdRoute
  AuthenticatedAnnouncementsIndexRoute: typeof AuthenticatedAnnouncementsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAntiraidRoute: AuthenticatedAntiraidRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedAutomodRoute: AuthenticatedAutomodRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedCommandsRoute: AuthenticatedCommandsRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPollsRoute: AuthenticatedPollsRoute,
  AuthenticatedRanksRoute: AuthenticatedRanksRoute,
  AuthenticatedSanctionsRoute: AuthenticatedSanctionsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedStaffRolesRoute: AuthenticatedStaffRolesRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedVersionsRoute: AuthenticatedVersionsRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnnouncementsIdRoute: AuthenticatedAnnouncementsIdRoute,
  AuthenticatedTicketIdRoute: AuthenticatedTicketIdRoute,
  AuthenticatedAnnouncementsIndexRoute: AuthenticatedAnnouncementsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
