/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAbsencesRouteImport } from './routes/_authenticated/absences'
import { Route as AuthenticatedAntinukeRouteImport } from './routes/_authenticated/antinuke'
import { Route as AuthenticatedAntiraidRouteImport } from './routes/_authenticated/antiraid'
import { Route as AuthenticatedAppealsRouteImport } from './routes/_authenticated/appeals'
import { Route as AuthenticatedArchivesRouteImport } from './routes/_authenticated/archives'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAutomodRouteImport } from './routes/_authenticated/automod'
import { Route as AuthenticatedBackupsRouteImport } from './routes/_authenticated/backups'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedChannelFeaturesRouteImport } from './routes/_authenticated/channel-features'
import { Route as AuthenticatedChannelSchedulesRouteImport } from './routes/_authenticated/channel-schedules'
import { Route as AuthenticatedCommandsRouteImport } from './routes/_authenticated/commands'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedCustomCommandsRouteImport } from './routes/_authenticated/custom-commands'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedDmsRouteImport } from './routes/_authenticated/dms'
import { Route as AuthenticatedEmbedsRouteImport } from './routes/_authenticated/embeds'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedFivemRouteImport } from './routes/_authenticated/fivem'
import { Route as AuthenticatedFivemEventsRouteImport } from './routes/_authenticated/fivem-events'
import { Route as AuthenticatedFivemPlayersRouteImport } from './routes/_authenticated/fivem-players'
import { Route as AuthenticatedGiveawaysRouteImport } from './routes/_authenticated/giveaways'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMusicRouteImport } from './routes/_authenticated/music'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedPollsRouteImport } from './routes/_authenticated/polls'
import { Route as AuthenticatedRanksRouteImport } from './routes/_authenticated/ranks'
import { Route as AuthenticatedRecruitmentRouteImport } from './routes/_authenticated/recruitment'
import { Route as AuthenticatedRpEventsRouteImport } from './routes/_authenticated/rp-events'
import { Route as AuthenticatedSanctionsRouteImport } from './routes/_authenticated/sanctions'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedStaffActivityRouteImport } from './routes/_authenticated/staff-activity'
import { Route as AuthenticatedStaffRolesRouteImport } from './routes/_authenticated/staff-roles'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedStreamsRouteImport } from './routes/_authenticated/streams'
import { Route as AuthenticatedTebexRouteImport } from './routes/_authenticated/tebex'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedVersionsRouteImport } from './routes/_authenticated/versions'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedAnnouncementsIndexRouteImport } from './routes/_authenticated/announcements/index'
import { Route as AuthenticatedAnnouncementsIdRouteImport } from './routes/_authenticated/announcements/$id'
import { Route as AuthenticatedTicketIdRouteImport } from './routes/_authenticated/ticket.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbsencesRoute = AuthenticatedAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAntinukeRoute = AuthenticatedAntinukeRouteImport.update({
  id: '/antinuke',
  path: '/antinuke',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAntiraidRoute = AuthenticatedAntiraidRouteImport.update({
  id: '/antiraid',
  path: '/antiraid',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppealsRoute = AuthenticatedAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchivesRoute = AuthenticatedArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomodRoute = AuthenticatedAutomodRouteImport.update({
  id: '/automod',
  path: '/automod',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupsRoute = AuthenticatedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelFeaturesRoute =
  AuthenticatedChannelFeaturesRouteImport.update({
    id: '/channel-features',
    path: '/channel-features',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChannelSchedulesRoute =
  AuthenticatedChannelSchedulesRouteImport.update({
    id: '/channel-schedules',
    path: '/channel-schedules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandsRoute = AuthenticatedCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomCommandsRoute =
  AuthenticatedCustomCommandsRouteImport.update({
    id: '/custom-commands',
    path: '/custom-commands',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDmsRoute = AuthenticatedDmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmbedsRoute = AuthenticatedEmbedsRouteImport.update({
  id: '/embeds',
  path: '/embeds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFivemRoute = AuthenticatedFivemRouteImport.update({
  id: '/fivem',
  path: '/fivem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFivemEventsRoute =
  AuthenticatedFivemEventsRouteImport.update({
    id: '/fivem-events',
    path: '/fivem-events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFivemPlayersRoute =
  AuthenticatedFivemPlayersRouteImport.update({
    id: '/fivem-players',
    path: '/fivem-players',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiveawaysRoute = AuthenticatedGiveawaysRouteImport.update({
  id: '/giveaways',
  path: '/giveaways',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicRoute = AuthenticatedMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPollsRoute = AuthenticatedPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRanksRoute = AuthenticatedRanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruitmentRoute =
  AuthenticatedRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRpEventsRoute = AuthenticatedRpEventsRouteImport.update({
  id: '/rp-events',
  path: '/rp-events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSanctionsRoute = AuthenticatedSanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffActivityRoute =
  AuthenticatedStaffActivityRouteImport.update({
    id: '/staff-activity',
    path: '/staff-activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffRolesRoute = AuthenticatedStaffRolesRouteImport.update({
  id: '/staff-roles',
  path: '/staff-roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStreamsRoute = AuthenticatedStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTebexRoute = AuthenticatedTebexRouteImport.update({
  id: '/tebex',
  path: '/tebex',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVersionsRoute = AuthenticatedVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsIndexRoute =
  AuthenticatedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsIdRoute =
  AuthenticatedAnnouncementsIdRouteImport.update({
    id: '/announcements/$id',
    path: '/announcements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketIdRoute = AuthenticatedTicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/antinuke': typeof AuthenticatedAntinukeRoute
  '/antiraid': typeof AuthenticatedAntiraidRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/archives': typeof AuthenticatedArchivesRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/automod': typeof AuthenticatedAutomodRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/channel-features': typeof AuthenticatedChannelFeaturesRoute
  '/channel-schedules': typeof AuthenticatedChannelSchedulesRoute
  '/commands': typeof AuthenticatedCommandsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/custom-commands': typeof AuthenticatedCustomCommandsRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/dms': typeof AuthenticatedDmsRoute
  '/embeds': typeof AuthenticatedEmbedsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/fivem': typeof AuthenticatedFivemRoute
  '/fivem-events': typeof AuthenticatedFivemEventsRoute
  '/fivem-players': typeof AuthenticatedFivemPlayersRoute
  '/giveaways': typeof AuthenticatedGiveawaysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/music': typeof AuthenticatedMusicRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/rp-events': typeof AuthenticatedRpEventsRoute
  '/sanctions': typeof AuthenticatedSanctionsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/staff-activity': typeof AuthenticatedStaffActivityRoute
  '/staff-roles': typeof AuthenticatedStaffRolesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/streams': typeof AuthenticatedStreamsRoute
  '/tebex': typeof AuthenticatedTebexRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/ticket/$id': typeof AuthenticatedTicketIdRoute
  '/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/antinuke': typeof AuthenticatedAntinukeRoute
  '/antiraid': typeof AuthenticatedAntiraidRoute
  '/appeals': typeof AuthenticatedAppealsRoute
  '/archives': typeof AuthenticatedArchivesRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/automod': typeof AuthenticatedAutomodRoute
  '/backups': typeof AuthenticatedBackupsRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/channel-features': typeof AuthenticatedChannelFeaturesRoute
  '/channel-schedules': typeof AuthenticatedChannelSchedulesRoute
  '/commands': typeof AuthenticatedCommandsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/custom-commands': typeof AuthenticatedCustomCommandsRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/dms': typeof AuthenticatedDmsRoute
  '/embeds': typeof AuthenticatedEmbedsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/fivem': typeof AuthenticatedFivemRoute
  '/fivem-events': typeof AuthenticatedFivemEventsRoute
  '/fivem-players': typeof AuthenticatedFivemPlayersRoute
  '/giveaways': typeof AuthenticatedGiveawaysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/music': typeof AuthenticatedMusicRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/polls': typeof AuthenticatedPollsRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/rp-events': typeof AuthenticatedRpEventsRoute
  '/sanctions': typeof AuthenticatedSanctionsRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/staff-activity': typeof AuthenticatedStaffActivityRoute
  '/staff-roles': typeof AuthenticatedStaffRolesRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/streams': typeof AuthenticatedStreamsRoute
  '/tebex': typeof AuthenticatedTebexRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/': typeof AuthenticatedIndexRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/ticket/$id': typeof AuthenticatedTicketIdRoute
  '/announcements': typeof AuthenticatedAnnouncementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/absences': typeof AuthenticatedAbsencesRoute
  '/_authenticated/antinuke': typeof AuthenticatedAntinukeRoute
  '/_authenticated/antiraid': typeof AuthenticatedAntiraidRoute
  '/_authenticated/appeals': typeof AuthenticatedAppealsRoute
  '/_authenticated/archives': typeof AuthenticatedArchivesRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/automod': typeof AuthenticatedAutomodRoute
  '/_authenticated/backups': typeof AuthenticatedBackupsRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/channel-features': typeof AuthenticatedChannelFeaturesRoute
  '/_authenticated/channel-schedules': typeof AuthenticatedChannelSchedulesRoute
  '/_authenticated/commands': typeof AuthenticatedCommandsRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/custom-commands': typeof AuthenticatedCustomCommandsRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/dms': typeof AuthenticatedDmsRoute
  '/_authenticated/embeds': typeof AuthenticatedEmbedsRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/fivem': typeof AuthenticatedFivemRoute
  '/_authenticated/fivem-events': typeof AuthenticatedFivemEventsRoute
  '/_authenticated/fivem-players': typeof AuthenticatedFivemPlayersRoute
  '/_authenticated/giveaways': typeof AuthenticatedGiveawaysRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/music': typeof AuthenticatedMusicRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/polls': typeof AuthenticatedPollsRoute
  '/_authenticated/ranks': typeof AuthenticatedRanksRoute
  '/_authenticated/recruitment': typeof AuthenticatedRecruitmentRoute
  '/_authenticated/rp-events': typeof AuthenticatedRpEventsRoute
  '/_authenticated/sanctions': typeof AuthenticatedSanctionsRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/staff-activity': typeof AuthenticatedStaffActivityRoute
  '/_authenticated/staff-roles': typeof AuthenticatedStaffRolesRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/streams': typeof AuthenticatedStreamsRoute
  '/_authenticated/tebex': typeof AuthenticatedTebexRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/versions': typeof AuthenticatedVersionsRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/_authenticated/ticket/$id': typeof AuthenticatedTicketIdRoute
  '/_authenticated/announcements/': typeof AuthenticatedAnnouncementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/absences'
    | '/antinuke'
    | '/antiraid'
    | '/appeals'
    | '/archives'
    | '/audit'
    | '/automod'
    | '/backups'
    | '/changelog'
    | '/channel-features'
    | '/channel-schedules'
    | '/commands'
    | '/console'
    | '/custom-commands'
    | '/developer'
    | '/dms'
    | '/embeds'
    | '/events'
    | '/feedback'
    | '/fivem'
    | '/fivem-events'
    | '/fivem-players'
    | '/giveaways'
    | '/logs'
    | '/meetings'
    | '/members'
    | '/messages'
    | '/music'
    | '/network'
    | '/onboarding'
    | '/people'
    | '/permissions'
    | '/polls'
    | '/ranks'
    | '/recruitment'
    | '/rp-events'
    | '/sanctions'
    | '/sessions'
    | '/staff-activity'
    | '/staff-roles'
    | '/stats'
    | '/streams'
    | '/tebex'
    | '/templates'
    | '/tickets'
    | '/verification'
    | '/versions'
    | '/voice'
    | '/announcements/$id'
    | '/ticket/$id'
    | '/announcements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/absences'
    | '/antinuke'
    | '/antiraid'
    | '/appeals'
    | '/archives'
    | '/audit'
    | '/automod'
    | '/backups'
    | '/changelog'
    | '/channel-features'
    | '/channel-schedules'
    | '/commands'
    | '/console'
    | '/custom-commands'
    | '/developer'
    | '/dms'
    | '/embeds'
    | '/events'
    | '/feedback'
    | '/fivem'
    | '/fivem-events'
    | '/fivem-players'
    | '/giveaways'
    | '/logs'
    | '/meetings'
    | '/members'
    | '/messages'
    | '/music'
    | '/network'
    | '/onboarding'
    | '/people'
    | '/permissions'
    | '/polls'
    | '/ranks'
    | '/recruitment'
    | '/rp-events'
    | '/sanctions'
    | '/sessions'
    | '/staff-activity'
    | '/staff-roles'
    | '/stats'
    | '/streams'
    | '/tebex'
    | '/templates'
    | '/tickets'
    | '/verification'
    | '/versions'
    | '/voice'
    | '/'
    | '/announcements/$id'
    | '/ticket/$id'
    | '/announcements'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/absences'
    | '/_authenticated/antinuke'
    | '/_authenticated/antiraid'
    | '/_authenticated/appeals'
    | '/_authenticated/archives'
    | '/_authenticated/audit'
    | '/_authenticated/automod'
    | '/_authenticated/backups'
    | '/_authenticated/changelog'
    | '/_authenticated/channel-features'
    | '/_authenticated/channel-schedules'
    | '/_authenticated/commands'
    | '/_authenticated/console'
    | '/_authenticated/custom-commands'
    | '/_authenticated/developer'
    | '/_authenticated/dms'
    | '/_authenticated/embeds'
    | '/_authenticated/events'
    | '/_authenticated/feedback'
    | '/_authenticated/fivem'
    | '/_authenticated/fivem-events'
    | '/_authenticated/fivem-players'
    | '/_authenticated/giveaways'
    | '/_authenticated/logs'
    | '/_authenticated/meetings'
    | '/_authenticated/members'
    | '/_authenticated/messages'
    | '/_authenticated/music'
    | '/_authenticated/network'
    | '/_authenticated/onboarding'
    | '/_authenticated/people'
    | '/_authenticated/permissions'
    | '/_authenticated/polls'
    | '/_authenticated/ranks'
    | '/_authenticated/recruitment'
    | '/_authenticated/rp-events'
    | '/_authenticated/sanctions'
    | '/_authenticated/sessions'
    | '/_authenticated/staff-activity'
    | '/_authenticated/staff-roles'
    | '/_authenticated/stats'
    | '/_authenticated/streams'
    | '/_authenticated/tebex'
    | '/_authenticated/templates'
    | '/_authenticated/tickets'
    | '/_authenticated/verification'
    | '/_authenticated/versions'
    | '/_authenticated/voice'
    | '/_authenticated/'
    | '/_authenticated/announcements/$id'
    | '/_authenticated/ticket/$id'
    | '/_authenticated/announcements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/absences': {
      id: '/_authenticated/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AuthenticatedAbsencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/antinuke': {
      id: '/_authenticated/antinuke'
      path: '/antinuke'
      fullPath: '/antinuke'
      preLoaderRoute: typeof AuthenticatedAntinukeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/antiraid': {
      id: '/_authenticated/antiraid'
      path: '/antiraid'
      fullPath: '/antiraid'
      preLoaderRoute: typeof AuthenticatedAntiraidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appeals': {
      id: '/_authenticated/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AuthenticatedAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archives': {
      id: '/_authenticated/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof AuthenticatedArchivesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automod': {
      id: '/_authenticated/automod'
      path: '/automod'
      fullPath: '/automod'
      preLoaderRoute: typeof AuthenticatedAutomodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backups': {
      id: '/_authenticated/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthenticatedBackupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel-features': {
      id: '/_authenticated/channel-features'
      path: '/channel-features'
      fullPath: '/channel-features'
      preLoaderRoute: typeof AuthenticatedChannelFeaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channel-schedules': {
      id: '/_authenticated/channel-schedules'
      path: '/channel-schedules'
      fullPath: '/channel-schedules'
      preLoaderRoute: typeof AuthenticatedChannelSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commands': {
      id: '/_authenticated/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof AuthenticatedCommandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custom-commands': {
      id: '/_authenticated/custom-commands'
      path: '/custom-commands'
      fullPath: '/custom-commands'
      preLoaderRoute: typeof AuthenticatedCustomCommandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dms': {
      id: '/_authenticated/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof AuthenticatedDmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/embeds': {
      id: '/_authenticated/embeds'
      path: '/embeds'
      fullPath: '/embeds'
      preLoaderRoute: typeof AuthenticatedEmbedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fivem': {
      id: '/_authenticated/fivem'
      path: '/fivem'
      fullPath: '/fivem'
      preLoaderRoute: typeof AuthenticatedFivemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fivem-events': {
      id: '/_authenticated/fivem-events'
      path: '/fivem-events'
      fullPath: '/fivem-events'
      preLoaderRoute: typeof AuthenticatedFivemEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fivem-players': {
      id: '/_authenticated/fivem-players'
      path: '/fivem-players'
      fullPath: '/fivem-players'
      preLoaderRoute: typeof AuthenticatedFivemPlayersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/giveaways': {
      id: '/_authenticated/giveaways'
      path: '/giveaways'
      fullPath: '/giveaways'
      preLoaderRoute: typeof AuthenticatedGiveawaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music': {
      id: '/_authenticated/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AuthenticatedMusicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/polls': {
      id: '/_authenticated/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthenticatedPollsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranks': {
      id: '/_authenticated/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof AuthenticatedRanksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruitment': {
      id: '/_authenticated/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedRecruitmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rp-events': {
      id: '/_authenticated/rp-events'
      path: '/rp-events'
      fullPath: '/rp-events'
      preLoaderRoute: typeof AuthenticatedRpEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sanctions': {
      id: '/_authenticated/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof AuthenticatedSanctionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-activity': {
      id: '/_authenticated/staff-activity'
      path: '/staff-activity'
      fullPath: '/staff-activity'
      preLoaderRoute: typeof AuthenticatedStaffActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-roles': {
      id: '/_authenticated/staff-roles'
      path: '/staff-roles'
      fullPath: '/staff-roles'
      preLoaderRoute: typeof AuthenticatedStaffRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/streams': {
      id: '/_authenticated/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof AuthenticatedStreamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tebex': {
      id: '/_authenticated/tebex'
      path: '/tebex'
      fullPath: '/tebex'
      preLoaderRoute: typeof AuthenticatedTebexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versions': {
      id: '/_authenticated/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof AuthenticatedVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/': {
      id: '/_authenticated/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements/$id': {
      id: '/_authenticated/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket/$id': {
      id: '/_authenticated/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof AuthenticatedTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbsencesRoute: typeof AuthenticatedAbsencesRoute
  AuthenticatedAntinukeRoute: typeof AuthenticatedAntinukeRoute
  AuthenticatedAntiraidRoute: typeof AuthenticatedAntiraidRoute
  AuthenticatedAppealsRoute: typeof AuthenticatedAppealsRoute
  AuthenticatedArchivesRoute: typeof AuthenticatedArchivesRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedAutomodRoute: typeof AuthenticatedAutomodRoute
  AuthenticatedBackupsRoute: typeof AuthenticatedBackupsRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedChannelFeaturesRoute: typeof AuthenticatedChannelFeaturesRoute
  AuthenticatedChannelSchedulesRoute: typeof AuthenticatedChannelSchedulesRoute
  AuthenticatedCommandsRoute: typeof AuthenticatedCommandsRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedCustomCommandsRoute: typeof AuthenticatedCustomCommandsRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedDmsRoute: typeof AuthenticatedDmsRoute
  AuthenticatedEmbedsRoute: typeof AuthenticatedEmbedsRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedFivemRoute: typeof AuthenticatedFivemRoute
  AuthenticatedFivemEventsRoute: typeof AuthenticatedFivemEventsRoute
  AuthenticatedFivemPlayersRoute: typeof AuthenticatedFivemPlayersRoute
  AuthenticatedGiveawaysRoute: typeof AuthenticatedGiveawaysRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMusicRoute: typeof AuthenticatedMusicRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPollsRoute: typeof AuthenticatedPollsRoute
  AuthenticatedRanksRoute: typeof AuthenticatedRanksRoute
  AuthenticatedRecruitmentRoute: typeof AuthenticatedRecruitmentRoute
  AuthenticatedRpEventsRoute: typeof AuthenticatedRpEventsRoute
  AuthenticatedSanctionsRoute: typeof AuthenticatedSanctionsRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedStaffActivityRoute: typeof AuthenticatedStaffActivityRoute
  AuthenticatedStaffRolesRoute: typeof AuthenticatedStaffRolesRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedStreamsRoute: typeof AuthenticatedStreamsRoute
  AuthenticatedTebexRoute: typeof AuthenticatedTebexRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedVersionsRoute: typeof AuthenticatedVersionsRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnnouncementsIdRoute: typeof AuthenticatedAnnouncementsIdRoute
  AuthenticatedTicketIdRoute: typeof AuthenticatedTicketIdRoute
  AuthenticatedAnnouncementsIndexRoute: typeof AuthenticatedAnnouncementsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbsencesRoute: AuthenticatedAbsencesRoute,
  AuthenticatedAntinukeRoute: AuthenticatedAntinukeRoute,
  AuthenticatedAntiraidRoute: AuthenticatedAntiraidRoute,
  AuthenticatedAppealsRoute: AuthenticatedAppealsRoute,
  AuthenticatedArchivesRoute: AuthenticatedArchivesRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedAutomodRoute: AuthenticatedAutomodRoute,
  AuthenticatedBackupsRoute: AuthenticatedBackupsRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedChannelFeaturesRoute: AuthenticatedChannelFeaturesRoute,
  AuthenticatedChannelSchedulesRoute: AuthenticatedChannelSchedulesRoute,
  AuthenticatedCommandsRoute: AuthenticatedCommandsRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedCustomCommandsRoute: AuthenticatedCustomCommandsRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedDmsRoute: AuthenticatedDmsRoute,
  AuthenticatedEmbedsRoute: AuthenticatedEmbedsRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedFivemRoute: AuthenticatedFivemRoute,
  AuthenticatedFivemEventsRoute: AuthenticatedFivemEventsRoute,
  AuthenticatedFivemPlayersRoute: AuthenticatedFivemPlayersRoute,
  AuthenticatedGiveawaysRoute: AuthenticatedGiveawaysRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMusicRoute: AuthenticatedMusicRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPollsRoute: AuthenticatedPollsRoute,
  AuthenticatedRanksRoute: AuthenticatedRanksRoute,
  AuthenticatedRecruitmentRoute: AuthenticatedRecruitmentRoute,
  AuthenticatedRpEventsRoute: AuthenticatedRpEventsRoute,
  AuthenticatedSanctionsRoute: AuthenticatedSanctionsRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedStaffActivityRoute: AuthenticatedStaffActivityRoute,
  AuthenticatedStaffRolesRoute: AuthenticatedStaffRolesRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedStreamsRoute: AuthenticatedStreamsRoute,
  AuthenticatedTebexRoute: AuthenticatedTebexRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedVersionsRoute: AuthenticatedVersionsRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnnouncementsIdRoute: AuthenticatedAnnouncementsIdRoute,
  AuthenticatedTicketIdRoute: AuthenticatedTicketIdRoute,
  AuthenticatedAnnouncementsIndexRoute: AuthenticatedAnnouncementsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
