/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated/network'
import { Route as AuthenticatedRanksRouteImport } from './routes/_authenticated/ranks'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedVersionsRouteImport } from './routes/_authenticated/versions'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRanksRoute = AuthenticatedRanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVersionsRoute = AuthenticatedVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/versions': typeof AuthenticatedVersionsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/ranks': typeof AuthenticatedRanksRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/versions': typeof AuthenticatedVersionsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/ranks': typeof AuthenticatedRanksRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/versions': typeof AuthenticatedVersionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/console'
    | '/logs'
    | '/members'
    | '/network'
    | '/ranks'
    | '/sessions'
    | '/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/console'
    | '/logs'
    | '/members'
    | '/network'
    | '/ranks'
    | '/sessions'
    | '/versions'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/audit'
    | '/_authenticated/console'
    | '/_authenticated/logs'
    | '/_authenticated/members'
    | '/_authenticated/network'
    | '/_authenticated/ranks'
    | '/_authenticated/sessions'
    | '/_authenticated/versions'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranks': {
      id: '/_authenticated/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof AuthenticatedRanksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versions': {
      id: '/_authenticated/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof AuthenticatedVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedRanksRoute: typeof AuthenticatedRanksRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedVersionsRoute: typeof AuthenticatedVersionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedRanksRoute: AuthenticatedRanksRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedVersionsRoute: AuthenticatedVersionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
